name: ‚ö° Version bump

on:
  workflow_run:
    workflows: ['‚ö° Coverage badges generation']
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-bump:
    name: üÜï Version bump
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: üì¶ Setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: ‚éî Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package.json

      - name: üì• Install deps
        run: bun install --frozen-lockfile

      - name: ‚è´ Bump package version
        id: bumping-version
        uses: ./
        with:
          debug: true
          major-keywords: BREAKING CHANGE
          minor-keywords: feat,minor
          patch-keywords: fix,chore
          should-default-to-patch: true
          commit-user: jpb06
          commit-user-email: jpb.06@outlook.com

      - name: Display action output
        run: |
          echo "Bump performed: ${{ steps.bumping-version.outputs.bump-performed }}"
          echo "New version: ${{ steps.bumping-version.outputs.new-version }}"

