name: âš¡ Version bump

on:
  push

jobs:
  version-bump:
    name: ğŸ†• Version bump
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: â« Bump package version
        id: bumping-version
        uses: .
          major-keywords: BREAKING CHANGE
          minor-keywords: feat,minor
          patch-keywords: fix,chore
          should-default-to-patch: false
          commit-user: jpb06
          commit-user-email: jpb.06@outlook.com