name: test

on: push

jobs:
  version-bump:
    name: ğŸ†• Version bump
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: testing stuff
        run: |
          jq . --raw-output "$GITHUB_EVENT_PATH"
